apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myapp:v1
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
          - name: config
            mountPath: /etc/config
            readOnly: true
        env:
          - name: ENV
            value: "dev"
      volumes:
        - name: config
          configMap:
            name: myapp-config
            items:
              - key: dev.yaml
                path: config.yaml
